# Generated by Django 2.2 on 2020-02-29 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
